[package]
name = "p01ars"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
polars = "0.38.3"
polars-arrow = "*" # for BitMap

savvy = { git = "https://github.com/yutannihilation/savvy" }
